"""
This type stub file was generated by pyright.
"""

from pyglet.input.base import Device

def ptr_add(ptr, offset): # -> _Pointer[Any]:
    ...

class DeviceResponder:
    ...


class XInputDevice(DeviceResponder, Device):
    def __init__(self, display, device_info) -> None:
        ...
    
    def get_controls(self): # -> list[Unknown]:
        ...
    
    def open(self, window=..., exclusive=...): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


class XInputWindowEventDispatcher:
    def __init__(self, window) -> None:
        ...
    
    @staticmethod
    def get_dispatcher(window): # -> XInputWindowEventDispatcher:
        ...
    
    def set_responder(self, device_id, responder): # -> None:
        ...
    
    def remove_responder(self, device_id): # -> None:
        ...
    
    def open_device(self, device_id, device, responder): # -> None:
        ...
    


def get_devices(display=...): # -> list[Unknown]:
    ...

