"""
This type stub file was generated by pyright.
"""

from pyglet.input.base import Tablet, TabletCanvas, TabletCursor
from pyglet.input.linux.x11_xinput import DeviceResponder

class XInputTablet(Tablet):
    name = ...
    def __init__(self, cursors) -> None:
        ...
    
    def open(self, window): # -> XInputTabletCanvas:
        ...
    


class XInputTabletCanvas(DeviceResponder, TabletCanvas):
    def __init__(self, window, cursors) -> None:
        ...
    
    def close(self): # -> None:
        ...
    


class XInputTabletCursor(TabletCursor):
    def __init__(self, device) -> None:
        ...
    


def get_tablets(display=...): # -> list[XInputTablet] | list[Unknown]:
    ...

