"""
This type stub file was generated by pyright.
"""

from ctypes import *
from .base import Canvas, Display, Screen, ScreenMode

class CocoaDisplay(Display):
    def get_screens(self): # -> list[CocoaScreen]:
        ...
    


class CocoaScreen(Screen):
    def __init__(self, display, displayID) -> None:
        ...
    
    def get_matching_configs(self, template):
        ...
    
    def get_modes(self): # -> list[CocoaScreenMode]:
        ...
    
    def get_mode(self): # -> CocoaScreenMode:
        ...
    
    def set_mode(self, mode): # -> None:
        ...
    
    def restore_mode(self): # -> None:
        ...
    
    def capture_display(self): # -> None:
        ...
    
    def release_display(self): # -> None:
        ...
    


class CocoaScreenMode(ScreenMode):
    def __init__(self, screen, cgmode) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def getBitsPerPixel(self, cgmode): # -> Literal[8, 16, 32, 0]:
        ...
    


class CocoaCanvas(Canvas):
    def __init__(self, display, screen, nsview) -> None:
        ...
    


