"""
This type stub file was generated by pyright.
"""

from ctypes import *
from pyglet.app.xlib import XlibSelectDevice
from .base import Canvas, Display, Screen, ScreenMode

class NoSuchDisplayException(Exception):
    ...


_error_handler_ptr = ...
class XlibDisplay(XlibSelectDevice, Display):
    _display = ...
    _x_im = ...
    _enable_xsync = ...
    _screens = ...
    def __init__(self, name=..., x_screen=...) -> None:
        ...
    
    def get_screens(self): # -> list[XlibScreen]:
        ...
    
    def fileno(self):
        ...
    
    def select(self): # -> None:
        ...
    
    def poll(self):
        ...
    


class XlibScreen(Screen):
    _initial_mode = ...
    def __init__(self, display, x, y, width, height, xinerama) -> None:
        ...
    
    def get_matching_configs(self, template):
        ...
    
    def get_modes(self): # -> list[Unknown]:
        ...
    
    def get_mode(self): # -> None:
        ...
    
    def set_mode(self, mode): # -> None:
        ...
    
    def restore_mode(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class XlibScreenMode(ScreenMode):
    def __init__(self, screen, info) -> None:
        ...
    


class XlibCanvas(Canvas):
    def __init__(self, display, x_window) -> None:
        ...
    


