"""
This type stub file was generated by pyright.
"""

from .darwin_hid import DarwinControllerManager as ControllerManager, get_apple_remote, get_controllers, get_devices, get_joysticks

def get_tablets(display=...): # -> list[Unknown]:
    ...

