"""
This type stub file was generated by pyright.
"""

import atexit
import pyglet

"""Drivers for playing back media."""
_debug = ...
def get_audio_driver(): # -> PulseAudioDriver | XAudio2Driver | DirectSoundDriver | OpenALDriver | SilentDriver:
    """Get the preferred audio driver for the current platform.

    Currently pyglet supports DirectSound, PulseAudio and OpenAL drivers. If
    the platform supports more than one of those audio drivers, the
    application can give its preference with :data:`pyglet.options` ``audio``
    keyword. See the Programming guide, section
    :doc:`/programming_guide/media`.

    Returns:
        AbstractAudioDriver : The concrete implementation of the preferred 
        audio driver for this platform.
    """
    ...

_audio_driver = ...
