"""
This type stub file was generated by pyright.
"""

"""Mouse constants and utilities for pyglet.window.
"""
class MouseStateHandler:
    """Simple handler that tracks the state of buttons from the mouse. If a
    button is pressed then this handler holds a True value for it.
    If the window loses focus, all buttons will be reset to False in order
    to avoid a "sticky" button state.

    For example::

        >>> win = window.Window()
        >>> mousebuttons = mouse.MouseStateHandler()
        >>> win.push_handlers(mousebuttons)

        # Hold down the "left" button...

        >>> mousebuttons[mouse.LEFT]
        True
        >>> mousebuttons[mouse.RIGHT]
        False

    """
    def __init__(self) -> None:
        ...
    
    def on_mouse_press(self, x, y, button, modifiers): # -> None:
        ...
    
    def on_mouse_release(self, x, y, button, modifiers): # -> None:
        ...
    
    def on_deactivate(self): # -> None:
        ...
    
    def on_mouse_motion(self, x, y, dx, dy): # -> None:
        ...
    
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers): # -> None:
        ...
    
    def __getitem__(self, key): # -> int | bool:
        ...
    


def buttons_string(buttons): # -> LiteralString:
    """Return a string describing a set of active mouse buttons.

    Example::

        >>> buttons_string(LEFT | RIGHT)
        'LEFT|RIGHT'

    :Parameters:
        `buttons` : int
            Bitwise combination of mouse button constants.

    :rtype: str
    """
    ...

LEFT = ...
MIDDLE = ...
RIGHT = ...
MOUSE4 = ...
MOUSE5 = ...
