"""
This type stub file was generated by pyright.
"""

import pyglet

"""Extensible attributed text format for representing pyglet formatted
documents.
"""
_pattern = ...
class AttributedTextDecoder(pyglet.text.DocumentDecoder):
    def __init__(self) -> None:
        ...
    
    def decode(self, text, location=...): # -> FormattedDocument:
        ...
    
    def append(self, text): # -> None:
        ...
    


