"""
This type stub file was generated by pyright.
"""

from html.parser import HTMLParser
from pyglet.text.formats import structured

"""Decode HTML into attributed text.

A subset of HTML 4.01 Transitional is implemented.  The following elements are
supported fully::

    B BLOCKQUOTE BR CENTER CODE DD DIR DL EM FONT H1 H2 H3 H4 H5 H6 I IMG KBD
    LI MENU OL P PRE Q SAMP STRONG SUB SUP TT U UL VAR 

The mark (bullet or number) of a list item is separated from the body of the
list item with a tab, as the pyglet document model does not allow
out-of-stream text.  This means lists display as expected, but behave a little
oddly if edited.

No CSS styling is supported.
"""
_color_names = ...
_whitespace_re = ...
_metadata_elements = ...
_block_elements = ...
_block_containers = ...
class HTMLDecoder(HTMLParser, structured.StructuredTextDecoder):
    """Decoder for HTML documents.
    """
    default_style = ...
    font_sizes = ...
    def decode_structured(self, text, location): # -> None:
        ...
    
    def get_image(self, filename): # -> Any:
        ...
    
    def prepare_for_data(self): # -> None:
        ...
    
    def handle_data(self, data): # -> None:
        ...
    
    def handle_starttag(self, tag, case_attrs):
        ...
    
    def handle_endtag(self, tag): # -> None:
        ...
    
    def handle_entityref(self, name): # -> None:
        ...
    
    def handle_charref(self, name): # -> None:
        ...
    


