"""
This type stub file was generated by pyright.
"""

import pyglet

"""Plain text decoder.
"""
class PlainTextDecoder(pyglet.text.DocumentDecoder):
    def decode(self, text, location=...): # -> UnformattedDocument:
        ...
    


