"""
This type stub file was generated by pyright.
"""

import pyglet
from pyglet.util import CodecRegistry, Decoder, Encoder
from .base import *

_debug = ...
registry = ...
add_decoders = ...
add_encoders = ...
get_decoders = ...
get_encoders = ...
class MediaDecoder(Decoder):
    def decode(self, filename, file, streaming):
        """Read the given file object and return an instance of `Source`
        or `StreamingSource`. 
        Throws DecodeException if there is an error.  `filename`
        can be a file type hint.
        """
        ...
    


class MediaEncoder(Encoder):
    def encode(self, source, filename, file):
        """Encode the given source to the given file.  `filename`
        provides a hint to the file format desired.  options are
        encoder-specific, and unknown options should be ignored or
        issue warnings.
        """
        ...
    


def add_default_codecs(): # -> None:
    ...

def have_ffmpeg(): # -> bool:
    """Check if FFmpeg library is available.

    Returns:
        bool: True if FFmpeg is found.

    .. versionadded:: 1.4
    """
    ...

