"""
This type stub file was generated by pyright.
"""

from pyglet.libs.darwin.cocoapy import NSRectEncoding, NSUIntegerEncoding

class PygletWindow_Implementation:
    PygletWindow = ...
    @PygletWindow.method('B')
    def canBecomeKeyWindow(self): # -> Literal[True]:
        ...
    
    @PygletWindow.method(b'@' + NSUIntegerEncoding + b'@@B')
    def nextEventMatchingMask_untilDate_inMode_dequeue_(self, mask, date, mode, dequeue): # -> int | Any:
        ...
    
    @PygletWindow.method(b'd' + NSRectEncoding)
    def animationResizeTime_(self, newFrame): # -> float:
        ...
    


class PygletToolWindow_Implementation:
    PygletToolWindow = ...
    @PygletToolWindow.method(b'@' + NSUIntegerEncoding + b'@@B')
    def nextEventMatchingMask_untilDate_inMode_dequeue_(self, mask, date, mode, dequeue): # -> int | Any:
        ...
    
    @PygletToolWindow.method(b'd' + NSRectEncoding)
    def animationResizeTime_(self, newFrame): # -> float:
        ...
    


PygletWindow = ...
PygletToolWindow = ...
