"""
This type stub file was generated by pyright.
"""

from pyglet.libs.darwin.cocoapy import PyObjectEncoding

NSNotificationCenter = ...
NSApplication = ...
class PygletDelegate_Implementation:
    PygletDelegate = ...
    @PygletDelegate.method(b'@' + PyObjectEncoding)
    def initWithWindow_(self, window): # -> None:
        ...
    
    @PygletDelegate.method('v')
    def dealloc(self): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def applicationDidHide_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def applicationDidUnhide_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('B@')
    def windowShouldClose_(self, notification): # -> Literal[False]:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidMove_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidBecomeKey_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidResignKey_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidMiniaturize_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidDeminiaturize_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def windowDidExpose_(self, notification): # -> None:
        ...
    
    @PygletDelegate.method('v@')
    def terminate_(self, sender): # -> None:
        ...
    
    @PygletDelegate.method('B@')
    def validateMenuItem_(self, menuitem): # -> bool:
        ...
    


PygletDelegate = ...
