"""
This type stub file was generated by pyright.
"""

from .libavcodec import *
from .libavutil import *
from .libavformat import *
from .libswresample import *
from .libswscale import *
from .compat import *

"""FFmpeg wrapping"""
