"""
This type stub file was generated by pyright.
"""

from ctypes import Structure

"""Wrapper for include/libswscale/swscale.h
"""
_debug = ...
swscale = ...
SWS_FAST_BILINEAR = ...
class SwsContext(Structure):
    ...


class SwsFilter(Structure):
    ...


__all__ = ['swscale', 'SWS_FAST_BILINEAR', 'SwsContext', 'SwsFilter']
