"""
This type stub file was generated by pyright.
"""

from pyglet.media.drivers.base import AbstractAudioDriver, AbstractAudioPlayer
from pyglet.media.drivers.listener import AbstractListener

_debug = ...
class XAudio2AudioPlayer(AbstractAudioPlayer):
    _cone_inner_angle = ...
    _cone_outer_angle = ...
    min_buffer_size = ...
    max_buffer_count = ...
    def __init__(self, driver, xa2_driver, source, player) -> None:
        ...
    
    def on_driver_destroy(self): # -> None:
        ...
    
    def on_driver_reset(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def delete(self): # -> None:
        """Called from Player. Docs says to cleanup resources, but other drivers wait for GC to do it?"""
        ...
    
    def play(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def refill_source_player(self): # -> None:
        """Obtains audio data from the source, puts it into a buffer to submit to the voice.
        Unlike the other drivers this does not carve pieces of audio from the buffer and slowly
        consume it. This submits the buffer retrieved from the decoder in it's entirety.
        """
        ...
    
    def get_time(self): # -> None:
        ...
    
    def set_volume(self, volume): # -> None:
        ...
    
    def set_position(self, position): # -> None:
        ...
    
    def set_min_distance(self, min_distance): # -> None:
        """Not a true min distance, but similar effect. Changes CurveDistanceScaler default is 1."""
        ...
    
    def set_max_distance(self, max_distance): # -> None:
        """No such thing built into xaudio2"""
        ...
    
    def set_pitch(self, pitch): # -> None:
        ...
    
    def set_cone_orientation(self, cone_orientation): # -> None:
        ...
    
    def set_cone_inner_angle(self, cone_inner_angle): # -> None:
        ...
    
    def set_cone_outer_angle(self, cone_outer_angle): # -> None:
        ...
    
    def set_cone_outer_gain(self, cone_outer_gain): # -> None:
        ...
    
    def prefill_audio(self): # -> None:
        ...
    


class XAudio2Driver(AbstractAudioDriver):
    def __init__(self) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def get_performance(self): # -> XAUDIO2_PERFORMANCE_DATA:
        ...
    
    def create_audio_player(self, source, player): # -> XAudio2AudioPlayer:
        ...
    
    def get_listener(self): # -> XAudio2Listener:
        ...
    
    def delete(self): # -> None:
        ...
    


class XAudio2Listener(AbstractListener):
    def __init__(self, xa2_listener, xa2_driver) -> None:
        ...
    


