"""
This type stub file was generated by pyright.
"""

from pyglet.gl import *

"""Byte abstractions of OpenGL Buffer Objects.

Use `create_buffer` to create a Buffer Object.

Buffers can optionally be created "mappable" (incorporating the
`AbstractMappable` mix-in).  In this case the buffer provides a ``get_region``
method which provides the most efficient path for updating partial data within
the buffer.
"""
class AbstractBuffer:
    """Abstract buffer of byte data.

    :Ivariables:
        `size` : int
            Size of buffer, in bytes
        `ptr` : int
            Memory offset of the buffer, as used by the ``glVertexPointer``
            family of functions
        `usage` : int
            OpenGL buffer usage, for example ``GL_DYNAMIC_DRAW``

    """
    ptr = ...
    size = ...
    def bind(self, target=...):
        """Bind this buffer to an OpenGL target."""
        ...
    
    def unbind(self):
        """Reset the buffer's OpenGL target."""
        ...
    
    def set_data(self, data):
        """Set the entire contents of the buffer.

        :Parameters:
            `data` : sequence of int or ctypes pointer
                The byte array to set.

        """
        ...
    
    def set_data_region(self, data, start, length):
        """Set part of the buffer contents.

        :Parameters:
            `data` : sequence of int or ctypes pointer
                The byte array of data to set
            `start` : int
                Offset to start replacing data
            `length` : int
                Length of region to replace

        """
        ...
    
    def map(self):
        """Map the entire buffer into system memory.

        The mapped region must be subsequently unmapped with `unmap` before
        performing any other operations on the buffer.

        :Parameters:
            `invalidate` : bool
                If True, the initial contents of the mapped block need not
                reflect the actual contents of the buffer.

        :rtype: ``POINTER(ctypes.c_ubyte)``
        :return: Pointer to the mapped block in memory
        """
        ...
    
    def unmap(self):
        """Unmap a previously mapped memory block."""
        ...
    
    def resize(self, size): # -> None:
        """Resize the buffer to a new size.

        :Parameters:
            `size` : int
                New size of the buffer, in bytes

        """
        ...
    
    def delete(self):
        """Delete this buffer, reducing system resource usage."""
        ...
    


class AbstractMappable:
    def get_region(self, start, size, ptr_type):
        """Map a region of the buffer into a ctypes array of the desired
        type.  This region does not need to be unmapped, but will become
        invalid if the buffer is resized.

        Note that although a pointer type is required, an array is mapped.
        For example::

            get_region(0, ctypes.sizeof(c_int) * 20, ctypes.POINTER(c_int * 20))

        will map bytes 0 to 80 of the buffer to an array of 20 ints.

        Changes to the array may not be recognised until the region's
        :py:meth:`AbstractBufferRegion.invalidate` method is called.

        :Parameters:
            `start` : int
                Offset into the buffer to map from, in bytes
            `size` : int
                Size of the buffer region to map, in bytes
            `ptr_type` : ctypes pointer type
                Pointer type describing the array format to create

        :rtype: :py:class:`AbstractBufferRegion`
        """
        ...
    


class BufferObject(AbstractBuffer):
    """Lightweight representation of an OpenGL Buffer Object.

    The data in the buffer is not replicated in any system memory (unless it
    is done so by the video driver).  While this can improve memory usage and
    possibly performance, updates to the buffer are relatively slow.
    The target of the buffer is ``GL_ARRAY_BUFFER`` internally to avoid
    accidentally overriding other states when altering the buffer contents.
    The intended target can be set when binding the buffer.

    This class does not implement :py:class:`AbstractMappable`, and so has no
    :py:meth:`~AbstractMappable.get_region` method.  See 
    :py:class:`MappableVertexBufferObject` for a Buffer class
    that does implement :py:meth:`~AbstractMappable.get_region`.
    """
    def __init__(self, size, usage=...) -> None:
        ...
    
    def invalidate(self): # -> None:
        ...
    
    def bind(self, target=...): # -> None:
        ...
    
    def unbind(self): # -> None:
        ...
    
    def bind_to_index_buffer(self): # -> None:
        """Binds this buffer as an index buffer on the active vertex array."""
        ...
    
    def set_data(self, data): # -> None:
        ...
    
    def set_data_region(self, data, start, length): # -> None:
        ...
    
    def map(self): # -> Array[c_byte]:
        ...
    
    def map_range(self, start, size, ptr_type):
        ...
    
    def unmap(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    def resize(self, size): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class MappableBufferObject(BufferObject, AbstractMappable):
    """A buffer with system-memory backed store.

    Updates to the data via `set_data`, `set_data_region` and `map` will be
    held in local memory until `bind` is called.  The advantage is that fewer
    OpenGL calls are needed, increasing performance.

    There may also be less performance penalty for resizing this buffer.

    Updates to data via :py:meth:`map` are committed immediately.
    """
    def __init__(self, size, usage=...) -> None:
        ...
    
    def bind(self): # -> None:
        ...
    
    def set_data(self, data): # -> None:
        ...
    
    def set_data_region(self, data, start, length): # -> None:
        ...
    
    def map(self, invalidate=...): # -> Array[c_byte]:
        ...
    
    def unmap(self): # -> None:
        ...
    
    def get_region(self, start, size, ptr_type): # -> BufferObjectRegion:
        ...
    
    def resize(self, size): # -> None:
        ...
    


class BufferObjectRegion:
    """A mapped region of a MappableBufferObject."""
    __slots__ = ...
    def __init__(self, buffer, start, end, array) -> None:
        ...
    
    def invalidate(self): # -> None:
        """Mark this region as changed.

        The buffer may not be updated with the latest contents of the
        array until this method is called.  (However, it may not be updated
        until the next time the buffer is used, for efficiency).
        """
        ...
    


