"""
This type stub file was generated by pyright.
"""

from ctypes import *
from typing import Any, Callable

__all__ = ['link_GL', 'link_GLX']
gl_lib = ...
def link_GL(name, restype, argtypes, requires=..., suggestions=...) -> Callable[..., Any]:
    ...

link_GLX = ...
