"""
This type stub file was generated by pyright.
"""

from .base import CanvasConfig, Config, Context
from pyglet.libs.win32.constants import *
from pyglet.libs.win32.types import *

class Win32Config(Config):
    def match(self, canvas): # -> list[Unknown] | list[Win32CanvasConfigARB] | list[Win32CanvasConfig]:
        ...
    


class Win32CanvasConfig(CanvasConfig):
    def __init__(self, canvas, pf, config) -> None:
        ...
    
    def compatible(self, canvas): # -> bool:
        ...
    
    def create_context(self, share): # -> Win32Context:
        ...
    


class Win32CanvasConfigARB(CanvasConfig):
    attribute_ids = ...
    def __init__(self, canvas, pf, config) -> None:
        ...
    
    def compatible(self, canvas): # -> bool:
        ...
    
    def create_context(self, share): # -> Win32ARBContext | Win32Context:
        ...
    


class Win32Context(Context):
    def __init__(self, config, share) -> None:
        ...
    
    def attach(self, canvas): # -> None:
        ...
    
    def set_current(self): # -> None:
        ...
    
    def detach(self): # -> None:
        ...
    
    def flip(self): # -> None:
        ...
    
    def get_vsync(self): # -> bool | None:
        ...
    
    def set_vsync(self, vsync): # -> None:
        ...
    


class Win32ARBContext(Win32Context):
    def __init__(self, config, share) -> None:
        ...
    
    def attach(self, canvas): # -> None:
        ...
    


