"""
This type stub file was generated by pyright.
"""

from pyglet.event import EventDispatcher

"""Display different types of interactive widgets.
"""
class WidgetBase(EventDispatcher):
    def __init__(self, x, y, width, height) -> None:
        ...
    
    def update_groups(self, order): # -> None:
        ...
    
    @property
    def x(self): # -> Unknown:
        """X coordinate of the widget.

        :type: int
        """
        ...
    
    @x.setter
    def x(self, value): # -> None:
        ...
    
    @property
    def y(self): # -> Unknown:
        """Y coordinate of the widget.

        :type: int
        """
        ...
    
    @y.setter
    def y(self, value): # -> None:
        ...
    
    @property
    def position(self): # -> tuple[Unknown, Unknown]:
        """The x, y coordinate of the widget as a tuple.

        :type: tuple(int, int)
        """
        ...
    
    @position.setter
    def position(self, values): # -> None:
        ...
    
    @property
    def width(self): # -> Unknown:
        """Width of the widget.

        :type: int
        """
        ...
    
    @property
    def height(self): # -> Unknown:
        """Height of the widget.

        :type: int
        """
        ...
    
    @property
    def aabb(self): # -> tuple[Unknown, Unknown, Unknown, Unknown]:
        """Bounding box of the widget.

        Expressed as (x, y, x + width, y + height)

        :type: (int, int, int, int)
        """
        ...
    
    @property
    def value(self):
        """Query or set the Widget's value.
        
        This property allows you to set the value of a Widget directly, without any
        user input.  This could be used, for example, to restore Widgets to a
        previous state, or if some event in your program is meant to naturally
        change the same value that the Widget controls.  Note that events are not
        dispatched when changing this property.
        """
        ...
    
    @value.setter
    def value(self, value):
        ...
    
    def on_mouse_press(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_release(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_motion(self, x, y, dx, dy): # -> None:
        ...
    
    def on_mouse_scroll(self, x, y, mouse, direction): # -> None:
        ...
    
    def on_text(self, text): # -> None:
        ...
    
    def on_text_motion(self, motion): # -> None:
        ...
    
    def on_text_motion_select(self, motion): # -> None:
        ...
    


class PushButton(WidgetBase):
    """Instance of a push button.

    Triggers the event 'on_press' when it is clicked by the mouse.
    Triggers the event 'on_release' when the mouse is released.
    """
    def __init__(self, x, y, pressed, depressed, hover=..., batch=..., group=...) -> None:
        """Create a push button.

        :Parameters:
            `x` : int
                X coordinate of the push button.
            `y` : int
                Y coordinate of the push button.
            `pressed` : `~pyglet.image.AbstractImage`
                Image to display when the button is pressed.
            `depresseed` : `~pyglet.image.AbstractImage`
                Image to display when the button isn't pressed.
            `hover` : `~pyglet.image.AbstractImage`
                Image to display when the button is being hovered over.
            `batch` : `~pyglet.graphics.Batch`
                Optional batch to add the push button to.
            `group` : `~pyglet.graphics.Group`
                Optional parent group of the push button.
        """
        ...
    
    @property
    def value(self): # -> bool:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    def update_groups(self, order): # -> None:
        ...
    
    def on_mouse_press(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_release(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_motion(self, x, y, dx, dy): # -> None:
        ...
    
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers): # -> None:
        ...
    


class ToggleButton(PushButton):
    """Instance of a toggle button.

    Triggers the event 'on_toggle' when the mouse is pressed or released.
    """
    def on_mouse_press(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_release(self, x, y, buttons, modifiers): # -> None:
        ...
    


class Slider(WidgetBase):
    """Instance of a slider made of a base and a knob image.

    Triggers the event 'on_change' when the knob position is changed.
    The knob position can be changed by dragging with the mouse, or
    scrolling the mouse wheel.
    """
    def __init__(self, x, y, base, knob, edge=..., batch=..., group=...) -> None:
        """Create a slider.

        :Parameters:
            `x` : int
                X coordinate of the slider.
            `y` : int
                Y coordinate of the slider.
            `base` : `~pyglet.image.AbstractImage`
                Image to display as the background to the slider.
            `knob` : `~pyglet.image.AbstractImage`
                Knob that moves to show the position of the slider.
            `edge` : int
                Pixels from the maximum and minimum position of the slider,
                to the edge of the base image.
            `batch` : `~pyglet.graphics.Batch`
                Optional batch to add the slider to.
            `group` : `~pyglet.graphics.Group`
                Optional parent group of the slider.
        """
        ...
    
    @property
    def value(self): # -> int:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    def update_groups(self, order): # -> None:
        ...
    
    def on_mouse_press(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_scroll(self, x, y, mouse, direction): # -> None:
        ...
    
    def on_mouse_release(self, x, y, buttons, modifiers): # -> None:
        ...
    


class TextEntry(WidgetBase):
    """Instance of a text entry widget.

    Allows the user to enter and submit text.
    """
    def __init__(self, text, x, y, width, color=..., text_color=..., caret_color=..., batch=..., group=...) -> None:
        """Create a text entry widget.

        :Parameters:
            `text` : str
                Initial text to display.
            `x` : int
                X coordinate of the text entry widget.
            `y` : int
                Y coordinate of the text entry widget.
            `width` : int
                The width of the text entry widget.
            `color` : (int, int, int, int)
                The color of the outline box in RGBA format.
            `text_color` : (int, int, int, int)
                The color of the text in RGBA format.
            `caret_color` : (int, int, int)
                The color of the caret in RGB format.
            `batch` : `~pyglet.graphics.Batch`
                Optional batch to add the text entry widget to.
            `group` : `~pyglet.graphics.Group`
                Optional parent group of text entry widget.
        """
        ...
    
    @property
    def value(self): # -> str:
        ...
    
    @value.setter
    def value(self, value): # -> None:
        ...
    
    def update_groups(self, order): # -> None:
        ...
    
    def on_mouse_motion(self, x, y, dx, dy): # -> None:
        ...
    
    def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers): # -> None:
        ...
    
    def on_mouse_press(self, x, y, buttons, modifiers): # -> None:
        ...
    
    def on_text(self, text): # -> None:
        ...
    
    def on_text_motion(self, motion): # -> None:
        ...
    
    def on_text_motion_select(self, motion): # -> None:
        ...
    
    def on_commit(self, text): # -> None:
        ...
    


