"""
This type stub file was generated by pyright.
"""

from .runtime import ObjCClass, ObjCInstance, ObjCSubclass, get_selector, objc, send_message, send_super
from .cocoatypes import *
from .cocoalibs import *

