"""
This type stub file was generated by pyright.
"""

from . import adaptation
from .exceptions import DirectSoundException, DirectSoundNativeError

def create_audio_driver(): # -> DirectSoundDriver:
    ...

__all__ = ["create_audio_driver", "DirectSoundException", "DirectSoundNativeError"]
