"""
This type stub file was generated by pyright.
"""

from pyglet.media.drivers.base import AbstractAudioDriver, AbstractAudioPlayer
from pyglet.media.drivers.listener import AbstractListener

_debug = ...
class PulseAudioDriver(AbstractAudioDriver):
    def __init__(self) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def create_audio_player(self, source, player): # -> PulseAudioPlayer:
        ...
    
    def connect(self, server=...): # -> None:
        """Connect to pulseaudio server.

        :Parameters:
            `server` : str
                Server to connect to, or ``None`` for the default local
                server (which may be spawned as a daemon if no server is
                found).
        """
        ...
    
    def dump_debug_info(self): # -> None:
        ...
    
    def delete(self): # -> None:
        """Completely shut down pulseaudio client."""
        ...
    
    def get_listener(self): # -> PulseAudioListener:
        ...
    


class PulseAudioListener(AbstractListener):
    def __init__(self, driver) -> None:
        ...
    


class PulseAudioPlayer(AbstractAudioPlayer):
    _volume = ...
    def __init__(self, source, player, driver) -> None:
        ...
    
    def on_write_needed(self, nbytes, underflow): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def play(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def get_time(self): # -> Literal[0]:
        ...
    
    def set_volume(self, volume): # -> None:
        ...
    
    def set_pitch(self, pitch): # -> None:
        ...
    
    def prefill_audio(self): # -> None:
        ...
    


