"""
This type stub file was generated by pyright.
"""

from pyglet.font import base

cf = ...
ct = ...
quartz = ...
class QuartzGlyphRenderer(base.GlyphRenderer):
    def __init__(self, font) -> None:
        ...
    
    def render(self, text):
        ...
    


class QuartzFont(base.Font):
    glyph_renderer_class = QuartzGlyphRenderer
    _loaded_CGFont_table = ...
    def __init__(self, name, size, bold=..., italic=..., stretch=..., dpi=...) -> None:
        ...
    
    @property
    def name(self): # -> str:
        ...
    
    def __del__(self): # -> None:
        ...
    
    @classmethod
    def have_font(cls, name): # -> bool:
        ...
    
    @classmethod
    def add_font_data(cls, data): # -> None:
        ...
    


