"""
This type stub file was generated by pyright.
"""

from pyglet.util import CodecRegistry, DecodeException, Decoder, EncodeException, Encoder

registry = ...
add_decoders = ...
add_encoders = ...
get_decoders = ...
get_encoders = ...
class ModelDecodeException(DecodeException):
    ...


class ModelEncodeException(EncodeException):
    ...


class ModelDecoder(Decoder):
    def decode(self, filename, file, batch, group):
        """Decode the given file object and return an instance of `Model`.
        Throws ModelDecodeException if there is an error.  filename
        can be a file type hint.
        """
        ...
    


class ModelEncoder(Encoder):
    def encode(self, model, filename, file):
        """Encode the given model to the given file.  filename
        provides a hint to the file format desired.  options are
        encoder-specific, and unknown options should be ignored or
        issue warnings.
        """
        ...
    


def add_default_codecs(): # -> None:
    ...

