"""
This type stub file was generated by pyright.
"""

from pyglet.app.base import PlatformEventLoop

class XlibSelectDevice:
    def fileno(self):
        """Get the file handle for ``select()`` for this device.

        :rtype: int
        """
        ...
    
    def select(self):
        """Perform event processing on the device.

        Called when ``select()`` returns this device in its list of active
        files.
        """
        ...
    
    def poll(self): # -> Literal[False]:
        """Check if the device has events ready to process.

        :rtype: bool
        :return: True if there are events to process, False otherwise.
        """
        ...
    


class NotificationDevice(XlibSelectDevice):
    def __init__(self) -> None:
        ...
    
    def fileno(self): # -> int:
        ...
    
    def set(self): # -> None:
        ...
    
    def select(self): # -> None:
        ...
    
    def poll(self): # -> bool:
        ...
    


class XlibEventLoop(PlatformEventLoop):
    def __init__(self) -> None:
        ...
    
    def notify(self): # -> None:
        ...
    
    def step(self, timeout=...): # -> bool:
        ...
    


