"""
This type stub file was generated by pyright.
"""

from pyglet.image import *
from pyglet.image.codecs import *

class PILImageDecoder(ImageDecoder):
    def get_file_extensions(self): # -> list[str]:
        ...
    
    def decode(self, filename, file): # -> ImageData:
        ...
    


class PILImageEncoder(ImageEncoder):
    def get_file_extensions(self): # -> list[str]:
        ...
    
    def encode(self, image, filename, file): # -> None:
        ...
    


def get_decoders(): # -> list[PILImageDecoder]:
    ...

def get_encoders(): # -> list[PILImageEncoder]:
    ...

