"""
This type stub file was generated by pyright.
"""

from pyglet.image.codecs import ImageDecoder, ImageEncoder

"""Encoder and decoder for PNG files, using PyPNG (png.py).
"""
class PNGImageDecoder(ImageDecoder):
    def get_file_extensions(self): # -> list[str]:
        ...
    
    def decode(self, filename, file): # -> ImageData:
        ...
    


class PNGImageEncoder(ImageEncoder):
    def get_file_extensions(self): # -> list[str]:
        ...
    
    def encode(self, image, filename, file): # -> None:
        ...
    


def get_decoders(): # -> list[PNGImageDecoder]:
    ...

def get_encoders(): # -> list[PNGImageEncoder]:
    ...

