"""
This type stub file was generated by pyright.
"""

from pyglet.media.drivers.base import AbstractAudioDriver, AbstractAudioPlayer
from pyglet.media.drivers.listener import AbstractListener

_debug = ...
class OpenALDriver(AbstractAudioDriver):
    def __init__(self, device_name=...) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def create_audio_player(self, source, player): # -> OpenALAudioPlayer:
        ...
    
    def delete(self): # -> None:
        ...
    
    def have_version(self, major, minor): # -> bool:
        ...
    
    def get_version(self): # -> tuple[int, int]:
        ...
    
    def get_extensions(self): # -> list[str]:
        ...
    
    def have_extension(self, extension): # -> bool:
        ...
    
    def get_listener(self): # -> OpenALListener:
        ...
    


class OpenALListener(AbstractListener):
    def __init__(self, driver) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


class OpenALAudioPlayer(AbstractAudioPlayer):
    min_buffer_size = ...
    _ideal_buffer_size = ...
    def __init__(self, driver, source, player) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def delete(self): # -> None:
        ...
    
    @property
    def ideal_buffer_size(self): # -> int:
        ...
    
    def play(self): # -> None:
        ...
    
    def stop(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    
    def refill_buffer(self): # -> bool:
        ...
    
    def get_time(self): # -> None:
        ...
    
    def set_volume(self, volume): # -> None:
        ...
    
    def set_position(self, position): # -> None:
        ...
    
    def set_min_distance(self, min_distance): # -> None:
        ...
    
    def set_max_distance(self, max_distance): # -> None:
        ...
    
    def set_pitch(self, pitch): # -> None:
        ...
    
    def set_cone_orientation(self, cone_orientation): # -> None:
        ...
    
    def set_cone_inner_angle(self, cone_inner_angle): # -> None:
        ...
    
    def set_cone_outer_angle(self, cone_outer_angle): # -> None:
        ...
    
    def set_cone_outer_gain(self, cone_outer_gain): # -> None:
        ...
    
    def prefill_audio(self): # -> None:
        ...
    


