"""
This type stub file was generated by pyright.
"""

import ctypes
import pyglet.libs.x11.xlib
from ctypes import *

"""Wrapper for Xinerama

Generated with:
tools/genwrappers.py xinerama

Do not modify this file.
"""
_lib = ...
_int_types = ...
if hasattr(ctypes, 'c_int64'):
    ...
class c_void(Structure):
    _fields_ = ...


class struct_anon_93(Structure):
    __slots__ = ...


XineramaScreenInfo = struct_anon_93
Display = pyglet.libs.x11.xlib.Display
XineramaQueryExtension = ...
XineramaQueryVersion = ...
XineramaIsActive = ...
XineramaQueryScreens = ...
__all__ = ['XineramaScreenInfo', 'XineramaQueryExtension', 'XineramaQueryVersion', 'XineramaIsActive', 'XineramaQueryScreens']
