"""
This type stub file was generated by pyright.
"""

"""
Responsabilities

    Handles accumulation of debug events while playing media_player and  saves
    when sample's play ends.
"""
class BufferedLogger:
    def __init__(self, outfile) -> None:
        ...
    
    def init_wall_time(self): # -> None:
        ...
    
    def log(self, *args): # -> None:
        ...
    
    def rebased_wall_time(self):
        ...
    
    def close(self): # -> None:
        ...
    
    def save_log_entries_as_pickle(self): # -> None:
        ...
    
    def clear(self): # -> None:
        ...
    


logger = ...
